PLUGIN_NAME       =		mtr
PLUGIN_VERSION    =		0.2
PLUGIN_DEVEL      =   "YES"
PLUGIN_COMMENT    =		Mtr is a plugin to see Who the IP address belongs to.
PLUGIN_MAINTAINER =	  mapa@max-it.de

.include "../../Mk/plugins.mk"
