PLUGIN_NAME=		whois
PLUGIN_VERSION=		0.1
PLUGIN_DEVEL= "YES"
PLUGIN_COMMENT=		Whois is a plugin to see Who the IP address belongs to.
PLUGIN_MAINTAINER=	mapa@max-it.de

.include "../../Mk/plugins.mk"
