PLUGIN_NAME       =		nmap
PLUGIN_VERSION    =		0.1
PLUGIN_DEVEL      =   "YES"
PLUGIN_DEPENDS    =   nmap
PLUGIN_COMMENT    =		Nmap is a plugin to see Who the IP address belongs to.
PLUGIN_MAINTAINER =	  mapa@max-it.de

.include "../../Mk/plugins.mk"
